'use client';

import { useEffect, useState } from 'react';
import { callFn } from '@/lib/fn';
import { CheckIcon, SpinnerIcon } from './icons';

interface Msg {
  when: string;
  kind: string;
  title: string;
  body: string;
  sent: boolean;
  sentAt: string | null;
  skipped: boolean;
  note: string | null;
}

interface Preview {
  station: string;
  city: string;
  watchers: number;
  publishedToday: boolean;
  devices: number;
  messages: Msg[];
}

/** What this station will hear from us today.
 *
 *  Generated by owner-daily itself rather than rebuilt here. Copying the three
 *  message texts into the admin panel would make them two things that have to
 *  be kept identical by hand — and a panel that shows a message nobody receives
 *  is worse than no panel, because it is believed. */
export function OwnerMessagePreview({ stationId }: { stationId: string }) {
  const [data, setData] = useState<Preview | null>(null);
  const [failed, setFailed] = useState<string | null>(null);

  useEffect(() => {
    callFn<Preview>(`owner-daily?preview=${stationId}`).then((r) =>
      r.ok && r.data ? setData(r.data) : setFailed(r.error ?? 'تعذّرت المعاينة')
    );
  }, [stationId]);

  return (
    <section className="card mt-4 p-5">
      <h2 className="text-sm font-bold">ماذا سيصل هذه المحطة اليوم</h2>
      <p className="mt-1 text-xs text-slate-400">
        النصّ نفسه الذي سترسله المنصة — مولَّد من الدالة المُرسِلة، لا مكتوباً هنا.
      </p>

      {!data && !failed && (
        <p className="mt-4 flex justify-center">
          <SpinnerIcon className="h-5 w-5 text-brand" />
        </p>
      )}

      {failed && (
        <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs leading-relaxed text-red-700">{failed}</p>
      )}

      {data && (
        <>
          {/* The message can be perfect and still reach nobody. This is the
              first thing to check, so it is the first thing shown. */}
          {data.devices === 0 && (
            <p className="mt-3 rounded-xl border-2 border-amber-300 bg-amber-50 p-3 text-xs leading-relaxed text-amber-900">
              <b>لا جهاز مربوط بهذه المحطة</b> — فلن يصلها أي إشعار مهما كان نصّه.
              يربط صاحبها جهازه بفتح لوحة محطته من التطبيق وهو داخل بحسابه.
            </p>
          )}

          <div className="mt-3 flex flex-wrap gap-2 text-[11px]">
            <span className="rounded-full bg-brand-50 px-2.5 py-1 font-bold text-brand-900">
              {data.watchers.toLocaleString('en-US')} مهتمّاً في {data.city}
            </span>
            <span
              className={`rounded-full px-2.5 py-1 font-bold ${
                data.publishedToday ? 'bg-brand-100 text-brand' : 'bg-red-50 text-traffic-red'
              }`}
            >
              {data.publishedToday ? 'نشرت اليوم' : 'لم تنشر اليوم'}
            </span>
            <span className="rounded-full bg-slate-100 px-2.5 py-1 font-bold text-slate-600">
              {data.devices} جهاز
            </span>
          </div>

          <ul className="mt-3 space-y-2">
            {data.messages.map((m) => (
              <li
                key={m.kind}
                className={`rounded-xl border p-3 ${
                  m.skipped ? 'border-slate-200 bg-slate-50 opacity-70' : 'border-brand-100 bg-white'
                }`}
              >
                <div className="flex items-center gap-2">
                  <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[11px] font-bold text-slate-600" dir="ltr">
                    {m.when}
                  </span>
                  {m.sent ? (
                    <span className="flex items-center gap-1 text-[11px] font-bold text-brand">
                      <CheckIcon className="h-3.5 w-3.5" />
                      أُرسلت
                      {m.sentAt ? ` ${m.sentAt.slice(11, 16)}` : ''}
                    </span>
                  ) : m.skipped ? (
                    <span className="text-[11px] font-bold text-slate-400">لن تُرسل</span>
                  ) : (
                    <span className="text-[11px] font-bold text-amber-700">بانتظار موعدها</span>
                  )}
                </div>
                <p className="mt-2 text-sm font-bold text-slate-800">{m.title}</p>
                <p className="mt-1 text-xs leading-relaxed text-slate-600">{m.body}</p>
                {m.note && <p className="mt-1.5 text-[11px] text-slate-400">{m.note}</p>}
              </li>
            ))}
          </ul>

          <p className="mt-3 text-[11px] leading-relaxed text-slate-400">
            ورسالةٌ رابعة تُرسل عند الحاجة لا بموعد: إن انتهى آخر تقييم ازدحام من
            الناس والمحطة مفتوحة، تُسأل لتؤكّد الحالة — مرة واحدة في اليوم.
          </p>
        </>
      )}
    </section>
  );
}
