'use client';
import {BADGE_LABELS,distanceLabel,iqd,ratingParts,time12,washBadge,type WashPublic} from '@/lib/wash';
import {WashUIIcon as Icon} from './WashUIIcon';
/** بطاقةُ المغسلة بلا صورة: الحالةُ والوسومُ والقلبُ في رأس الجسم — الصورُ في صفحة التفاصيل. */
export function WashCard({w,services,nextSlot,fav,onFav}:{w:WashPublic;services:{name:string;price:number}[];nextSlot:string|null|undefined;fav:boolean;onFav:(id:string)=>void}) {
 const badge=washBadge(w,nextSlot), rating=ratingParts(w.rating_avg,w.rating_n),dist=distanceLabel(w.distanceKm);
 const canBook=!w.temp_closed&&!w.paused&&services.length>0;
 const detail=`/wash/detail/?id=${encodeURIComponent(w.id)}`;
 return <article className="wash-card">
 <div className="wash-card-body"><div className="wash-card-head"><span className={`wash-status wash-status-${badge}`}><i/>{BADGE_LABELS[badge]}</span><div className="wash-card-tags">{w.sponsored?<span>إعلان</span>:w.featured&&<span>مغسلة مميزة</span>}{w.has_offer&&<span className="wash-offer-tag"><Icon name="tag" size={12}/>عرض متاح</span>}</div><button className="wash-heart" aria-label={`${fav?'إزالة':'إضافة'} ${w.name} ${fav?'من':'إلى'} المفضلة`} aria-pressed={fav} onClick={()=>onFav(w.id)}><Icon name="heart" size={18} filled={fav}/></button></div><div className="wash-card-title"><h3><a href={detail}>{w.name}</a></h3>{rating?<span className="wash-rating"><Icon name="star" size={14} filled/><b>{rating.avg}</b><small>({rating.count})</small></span>:<small className="wash-unrated">جديدة</small>}</div><p className="wash-location"><Icon name="pin" size={15}/>{w.city}{w.area?`، ${w.area}`:''}{dist&&<span>· {dist}</span>}</p><div className="wash-service-list">{services.slice(0,3).map((s,i)=><span key={i}>{s.name}</span>)}</div><div className="wash-availability"><Icon name="clock" size={15}/><span>{nextSlot&&canBook?`أقرب موعد اليوم ${time12(nextSlot)}`:nextSlot===null&&canBook?'استعرض مواعيد الأيام القادمة':w.temp_closed?'مغلقة مؤقتاً':w.paused?'الحجوزات متوقفة مؤقتاً':w.is_24h?'تعمل على مدار الساعة':'التفاصيل ومواعيد العمل داخل المغسلة'}</span></div><div className="wash-card-bottom"><div className="wash-price"><small>الغسلة تبدأ من</small><strong>{w.from_price!=null?iqd(w.from_price):'استعلم عن السعر'}</strong></div><a className="wash-primary" href={canBook?`/wash/book/?id=${encodeURIComponent(w.id)}`:detail}>{canBook?'احجز موعدك':'التفاصيل'}<Icon name="arrow" size={17}/></a></div></div></article>;
}
